"""add description to workspaces

Revision ID: 736e197acb6c
Revises: 
Create Date: 2026-05-20 16:06:31.463835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '736e197acb6c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_ai_suggestions_file_id'), table_name='ai_suggestions')
    op.drop_index(op.f('idx_ai_suggestions_status'), table_name='ai_suggestions')
    op.drop_index(op.f('idx_ai_suggestions_suggested_by'), table_name='ai_suggestions')
    op.drop_table('ai_suggestions')
    op.drop_index(op.f('idx_files_created_by'), table_name='files')
    op.drop_index(op.f('idx_files_path'), table_name='files')
    op.drop_index(op.f('idx_files_repository_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('idx_repositories_workspace_id'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_table('github_tokens')
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'display_name')
    op.add_column('workspaces', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('workspaces', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('workspaces', 'owner_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               nullable=True)
    op.drop_index(op.f('idx_workspaces_owner_id'), table_name='workspaces')
    op.drop_index(op.f('idx_workspaces_slug'), table_name='workspaces')
    op.drop_constraint(op.f('workspaces_owner_name_unique'), 'workspaces', type_='unique')
    op.drop_constraint(op.f('workspaces_slug_key'), 'workspaces', type_='unique')
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    op.drop_constraint(op.f('workspaces_owner_id_fkey'), 'workspaces', type_='foreignkey')
    op.create_foreign_key(None, 'workspaces', 'users', ['owner_id'], ['id'])
    op.drop_column('workspaces', 'created_at')
    op.drop_column('workspaces', 'updated_at')
    op.drop_column('workspaces', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('slug', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('workspaces', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('workspaces', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.create_foreign_key(op.f('workspaces_owner_id_fkey'), 'workspaces', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.create_unique_constraint(op.f('workspaces_slug_key'), 'workspaces', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('workspaces_owner_name_unique'), 'workspaces', ['owner_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_workspaces_slug'), 'workspaces', ['slug'], unique=False)
    op.create_index(op.f('idx_workspaces_owner_id'), 'workspaces', ['owner_id'], unique=False)
    op.alter_column('workspaces', 'owner_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               nullable=False)
    op.alter_column('workspaces', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_column('workspaces', 'description')
    op.add_column('users', sa.Column('display_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_column('users', 'username')
    op.create_table('github_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('github_tokens_pkey'))
    )
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('default_branch', sa.VARCHAR(length=80), server_default=sa.text("'main'::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_private', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('repositories_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('repositories_pkey')),
    sa.UniqueConstraint('workspace_id', 'name', name=op.f('repositories_workspace_name_unique'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_repositories_workspace_id'), 'repositories', ['workspace_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('repository_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('length(TRIM(BOTH FROM path)) > 0', name=op.f('files_path_not_empty')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('files_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('files_repository_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('files_pkey')),
    sa.UniqueConstraint('repository_id', 'path', name=op.f('files_repository_path_unique'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_files_repository_id'), 'files', ['repository_id'], unique=False)
    op.create_index(op.f('idx_files_path'), 'files', ['path'], unique=False)
    op.create_index(op.f('idx_files_created_by'), 'files', ['created_by'], unique=False)
    op.create_table('ai_suggestions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('suggested_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('suggestion_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("status::text = ANY (ARRAY['pending'::character varying, 'accepted'::character varying, 'rejected'::character varying, 'applied'::character varying]::text[])", name=op.f('ai_suggestions_status_check')),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('ai_suggestions_file_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suggested_by'], ['users.id'], name=op.f('ai_suggestions_suggested_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_suggestions_pkey'))
    )
    op.create_index(op.f('idx_ai_suggestions_suggested_by'), 'ai_suggestions', ['suggested_by'], unique=False)
    op.create_index(op.f('idx_ai_suggestions_status'), 'ai_suggestions', ['status'], unique=False)
    op.create_index(op.f('idx_ai_suggestions_file_id'), 'ai_suggestions', ['file_id'], unique=False)
    # ### end Alembic commands ###
